Codigo SEGMENT
    Assume CS: Codigo;DS:Codigo; ES: Codigo; SS:Codigo
    Org 100H
Entrada: JMP Nomeprog

            VAR1 DB 'DIGITE O PRIMEIRO  NUMERO: $'
            PULALINHA DB 0AH,0DH		;0ah,0ah,0dh,'$'
            VAR2 DB 'DIGITE O SEGUNDO  NUMERO: $'
            VAR3 DB 'RESULTADO$'

Nomeprog PROC NEAR

	LEA DX, OFFSET VAR1
	CALL MOSTRASTRING
	MOV BL,AL

	LEA DX, OFFSET PULALINHA
	CALL MOSTRASTRING
	LEA DX, OFFSET VAR1

	CALL MOSTRASTRING
	MOV CL, AL

	ADD CL,BL
	MOV AL, CL
	MOV AH, 0

	AAA

	OR AX,3030H

	MOV BX,AX
	MOV DL, BH
	CALL MOSTRACHAR

	MOV DL,BL
	CALL MOSTRACHAR

	INT 20H

MOSTRASTRING PROC NEAR
	MOV AH, 09H
	INT 21H
	RET

MOSTRASTRING ENDP


MOSTRACHAR PROC NEAR
	MOV AH, 02H
	INT 21H
	RET

MOSTRACHAR ENDP

Nomeprog ENDP

Codigo ENDS