MOV AH, 01H
INT 21H
; AL <- CODIGO ASCII DO QUE FOI DIGITADO
MOV CL, AL; SALVA PRIMEIRO NUMERO EM CL
MOV AH, 01H
INT 21H
MOV BL,AL ; SALVA SEGUNDO NÚMERO EM BL
ADD  BL, CL ; BL<-BL+CL
MOV AH, 0
MOV AL, CL ; AL<-CL PARA AJUSTE
AAA ; ASCII ADJUST FOR ADDITION
OR AX, 3030H ; COLOCA EM ASCII DE VOLTA
MOV CX, AX
MOV DL, CH
MOV AH, 02H ; MOSTRA DEZENA
INT 21H
MOV DL,CL
MOV AH, 02H ; MOSTRA UNIDADE
INT 21H